FROM oven/bun:1.3-alpine
WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --production=false

COPY drizzle.config.ts ./
COPY drizzle ./drizzle

CMD ["bunx", "drizzle-kit", "migrate"]
